### ISSUE TITLE
7- Check if everything is working perfectly

### ISSUE THREAD

**Issue by samirm00** [samirm00/Tom#10]
Double check if everything is working properly

**Comment by KrystynaMil** [comment]
I will check it when MarieBelyse will finish her issue :)

**Comment by samirm00** [comment]
@KrystynaMil  yes , we have to wait until Marie is done !

**Comment by Houcinos** [comment]
@MarieBelyse do you have any timeline to finalize this task? please let us know if you need help from one of us or from Unmesh.

**Comment by MarieBelyse** [comment]
Hi Houcinos, I am going ask my question during our meeting on that and finalize my task before end of today. Thank you for kind reminder. On 12 Oct 2020 11:25, Houcinos <notifications@github.com> wrote:
@MarieBelyse do you have any timeline to finalize this task? please let us know if you need help from one of us or from Unmesh.

**Comment by KrystynaMil** [comment]
Check for everything.

**Comment by samirm00** [comment]
Good to go

**Comment by MarieBelyse** [comment]
I did the repo
